# Generated by Django 4.1.3 on 2023-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinas',
            name='ejercicios',
            field=models.CharField(max_length=300),
        ),
    ]
